# Generated by Django 5.0.2 on 2024-02-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('news', 'News')], default='blog', max_length=4),
        ),
    ]
